/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeStack */

#ifndef _Included_NativeStack
#define _Included_NativeStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeStack
 * Method:    nativePush
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_NativeStack_nativePush
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     NativeStack
 * Method:    nativeGet
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_NativeStack_nativeGet
  (JNIEnv *, jobject);

/*
 * Class:     NativeStack
 * Method:    nativePop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeStack_nativePop
  (JNIEnv *, jobject);

/*
 * Class:     NativeStack
 * Method:    nativeIsEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_NativeStack_nativeIsEmpty
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
